export const mockAnalytics = {
  totalItems: 342,
  lowStockItems: 23,
  outOfStockItems: 8,
  totalValue: 45670,
  monthlyConsumption: 12450,
  topCategories: [
    { category: "Housekeeping", items: 89, value: 15420, percentage: 33.8 },
    {
      category: "Food & Beverage",
      items: 76,
      value: 12890,
      percentage: 28.2,
    },
    { category: "Maintenance", items: 54, value: 8760, percentage: 19.2 },
    { category: "Office Supplies", items: 43, value: 5230, percentage: 11.4 },
    { category: "Guest Amenities", items: 80, value: 3370, percentage: 7.4 },
  ],
  lowStockItems: [
    {
      name: "Toilet Paper",
      category: "Housekeeping",
      current: 15,
      minimum: 50,
      unit: "rolls",
    },
    {
      name: "Coffee Beans",
      category: "Food & Beverage",
      current: 8,
      minimum: 25,
      unit: "kg",
    },
    {
      name: "Towels",
      category: "Housekeeping",
      current: 12,
      minimum: 30,
      unit: "pieces",
    },
    {
      name: "Cleaning Spray",
      category: "Housekeeping",
      current: 5,
      minimum: 20,
      unit: "bottles",
    },
    {
      name: "Printer Paper",
      category: "Office Supplies",
      current: 3,
      minimum: 15,
      unit: "reams",
    },
  ],
  monthlyTrends: [
    { month: "Jan", consumption: 11200, purchases: 15600, value: 42000 },
    { month: "Feb", consumption: 10800, purchases: 12400, value: 43600 },
    { month: "Mar", consumption: 12100, purchases: 14200, value: 45800 },
    { month: "Apr", consumption: 11900, purchases: 13800, value: 47200 },
    { month: "May", consumption: 12450, purchases: 15200, value: 45670 },
    { month: "Jun", consumption: 11750, purchases: 14600, value: 46800 },
  ],
  recentTransactions: [
    {
      id: "TXN-001",
      type: "Purchase",
      item: "Bed Sheets",
      quantity: 50,
      amount: 1250,
      date: "2024-06-15",
    },
    {
      id: "TXN-002",
      type: "Consumption",
      item: "Shampoo",
      quantity: -25,
      amount: -375,
      date: "2024-06-14",
    },
    {
      id: "TXN-003",
      type: "Purchase",
      item: "Kitchen Utensils",
      quantity: 30,
      amount: 890,
      date: "2024-06-13",
    },
    {
      id: "TXN-004",
      type: "Consumption",
      item: "Toilet Paper",
      quantity: -40,
      amount: -120,
      date: "2024-06-12",
    },
    {
      id: "TXN-005",
      type: "Purchase",
      item: "Cleaning Supplies",
      quantity: 75,
      amount: 2250,
      date: "2024-06-11",
    },
  ],
};
